site_name: max ho portfolio
site_url: https://sitename.example

nav:
  - 'knime_etl.md'
  - 'power_bi_python.md'
  - 'classification_mushroom_edibility.md'
  - 'R_code_for_mushroom_edibility_classification_project.html'

theme:
    name: material
    logo: images/fish.svg
    favicon: images/fish.svg
    features: 
        - content.code.annotate

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

markdown_extensions:
    - admonition
    - attr_list
    - def_list
    - md_in_html
    - tables
    - pymdownx.blocks.caption
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
        slugify: !!python/object/apply:pymdownx.slugs.slugify
            kwds:
                case: lower
    - pymdownx.arithmatex:
        generic: true
    
extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
